os: linux
dist: jammy
language: python

python:
  - "3.9"

install:
  - gem install webrick
  - pip install -r symbi/requirements.txt

before_script:
  - cd symbi
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls -r $COVERALLS_REPO_TOKEN

# deploy:
#   provider: elasticbeanstalk
#   access_key_id: $AWS_ACCESS_KEY_ID
#   secret_access_key: $AWS_SECRET_ACCESS_KEY
#   region: $AWS_REGION
#   app: "symbi"
#   env: $AWS_EBS_EV
#   bucket_name: "$AWS_BUCKET_NAME"
#   on:
#     branch: develop
