os: linux
dist: jammy
language: python

python:
  - "3.9"

install:
  - gem install webrick
  - pip install -r requirements.txt

before_script:
  - python manage.py migrate

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls
