os: linux
dist: jammy
language: python

python:
  - "3.9"

install:
  - gem install webrick
  - pip install -r symbi/requirements.txt
  - npm install symbi/theme/static_src
  - npm install symbi


before_script:
  - cd symbi
  - python manage.py migrate
  - python manage.py collectstatic --noinput
  - python manage.py tailwind build

script:
  - black --check .
  - flake8 .
  - coverage run manage.py test

after_success:
  - curl -sL https://coveralls.io/coveralls-linux.tar.gz | tar -xz && ./coveralls -r $COVERALLS_REPO_TOKEN

deploy:
  provider: elasticbeanstalk
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: $AWS_REGION
  app: "symbi"
  env: symbi-env
  bucket_name: $AWS_BUCKET_NAME
  on:
    branch: master
