# Generated by Django 4.2.6 on 2023-10-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socialuser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='pronouns',
            field=models.CharField(choices=[('he/him', 'He/Him'), ('she/her', 'She/Her'), ('they/them', 'They/Them'), ('other', 'Other')], default='she/her', max_length=9),
        ),
    ]
