# Generated by Django 4.2.6 on 2023-11-06 17:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialuser",
            name="date_of_birth",
            field=models.DateField(default="2000-01-01"),
        ),
    ]
