# Generated by Django 4.2.6 on 2023-11-21 18:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialuser",
            name="age",
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="email",
            field=models.EmailField(default="@nyu.edu", max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="full_name",
            field=models.CharField(default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="pronouns",
            field=models.IntegerField(
                choices=[
                    (1, "She/Her"),
                    (2, "He/Him"),
                    (3, "They/Them"),
                    (4, "Other/Prefer Not To Say"),
                ],
                default=4,
            ),
        ),
    ]
