# Generated by Django 4.2.6 on 2023-11-10 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_socialuser_timestamp_notification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialuser",
            name="connections",
        ),
        migrations.AddField(
            model_name="socialuser",
            name="profile_picture",
            field=models.ImageField(blank=True, null=True, upload_to="profile_pics/"),
        ),
    ]
