# Generated by Django 4.2.6 on 2023-11-06 18:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_socialuser_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="InterestTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name="socialuser",
            name="age",
            field=models.IntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
        migrations.AddField(
            model_name="socialuser",
            name="major",
            field=models.CharField(default="undeclared", max_length=100),
        ),
        migrations.AddField(
            model_name="socialuser",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="main.interesttag"),
        ),
    ]
