# Generated by Django 4.2.6 on 2023-12-05 23:27

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0002_block"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="date_of_birth",
            field=models.DateField(null=True, validators=[main.models.validate_age]),
        ),
    ]
