# Generated by Django 4.2.6 on 2023-12-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_alter_socialuser_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="url",
            field=models.TextField(default=" "),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Connection Request"), (2, "New Comment"), (3, "Tagged")]
            ),
        ),
    ]
