# Generated by Django 4.2.6 on 2023-11-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0003_remove_socialuser_connections_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.IntegerField(
                choices=[(1, "Connection Request"), (2, "New Comment")]
            ),
        ),
    ]
