# Generated by Django 4.2.6 on 2023-11-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_socialuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interesttag",
            options={"verbose_name_plural": "Interest Tags"},
        ),
        migrations.AddField(
            model_name="socialuser",
            name="full_name",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="age",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="socialuser",
            name="date_of_birth",
            field=models.DateField(),
        ),
        migrations.AlterModelTable(
            name="interesttag",
            table="interest_tags",
        ),
    ]
