# Generated by Django 4.2.6 on 2023-11-07 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_socialuser_username"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="interesttag",
            options={"verbose_name_plural": "Interest Tags"},
        ),
        migrations.AlterModelTable(
            name="interesttag",
            table="interest_tags",
        ),
    ]
