# Generated by Django 4.2.6 on 2023-12-07 23:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_userreport"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userreport",
            unique_together={("reporter", "object_id", "report_category")},
        ),
    ]
