# Generated by Django 4.2.6 on 2023-11-08 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_interesttag_options_alter_interesttag_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="pronouns",
            field=models.IntegerField(
                choices=[(1, "She/Her"), (2, "He/Him"), (3, "They/Them"), (4, "Other")],
                default=4,
            ),
        ),
        migrations.CreateModel(
            name="Connection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(verbose_name="date connected")),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (1, "Not Connected"),
                            (2, "Requested A -> B"),
                            (3, "Requested B -> A"),
                            (4, "Connected"),
                            (5, "Blocked"),
                        ],
                        default=1,
                    ),
                ),
                (
                    "socialuser",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connections",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "userB",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userB",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
