# Generated by Django 4.2.6 on 2023-11-11 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_remove_notification_user_notification_from_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="connection",
            name="notification",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="main.notification",
            ),
        ),
    ]
