# Generated by Django 4.2.6 on 2023-11-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0005_alter_interesttag_options_socialuser_full_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialuser",
            name="date_of_birth",
            field=models.DateField(null=True),
        ),
    ]
