# Generated by Django 4.2.6 on 2023-12-08 00:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("main", "0005_alter_userreport_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="userreport",
            unique_together={
                ("reporter", "content_type", "object_id", "report_category")
            },
        ),
    ]
