# Generated by Django 4.2.6 on 2023-11-08 23:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_socialuser_date_of_birth"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="socialuser",
            name="age",
        ),
    ]
