# Generated by Django 4.2.6 on 2023-12-08 06:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_notification_url_alter_notification_type"),
        ("main", "0006_alter_userreport_unique_together"),
    ]

    operations = []
