# Generated by Django 4.2.6 on 2023-11-08 23:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0007_remove_socialuser_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="socialuser",
            name="age",
            field=models.IntegerField(
                default=18,
                validators=[
                    django.core.validators.MinValueValidator(18),
                    django.core.validators.MaxValueValidator(150),
                ],
            ),
        ),
    ]
