# Generated by Django 4.2.6 on 2023-11-10 18:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0006_alter_socialuser_pronouns_connection"),
        ("main", "0008_socialuser_age"),
    ]

    operations = []
