# Generated by Django 4.2.6 on 2023-12-04 08:01

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="taggedUsers",
            field=models.ManyToManyField(
                related_name="taggedUsers", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
