# Generated by Django 4.2.6 on 2023-11-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("main", "0004_alter_socialuser_username"),
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ActivityTag",
        ),
        migrations.AlterField(
            model_name="activitypost",
            name="tags",
            field=models.ManyToManyField(to="main.interesttag"),
        ),
    ]
