# Generated by Django 4.2.6 on 2023-11-07 23:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("posts", "0002_delete_activitytag_alter_activitypost_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitypost",
            name="description",
            field=models.TextField(max_length=1023),
        ),
        migrations.AlterField(
            model_name="activitypost",
            name="poster",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="activitypost",
            name="status",
            field=models.IntegerField(
                choices=[(1, "Draft"), (2, "Active"), (3, "Archived")], default=1
            ),
        ),
        migrations.AlterField(
            model_name="activitypost",
            name="title",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterModelTable(
            name="activitypost",
            table="activity_posts",
        ),
    ]
