# Generated by Django 4.2.6 on 2023-12-07 23:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="report",
            name="reason",
            field=models.IntegerField(
                choices=[
                    (1, "Hate speech or symbols"),
                    (2, "Abuse and harassment"),
                    (3, "Violence or dangerous organizations"),
                    (4, "Privacy"),
                    (5, "Spam"),
                    (6, "Sensitive or Disturbing Media"),
                    (7, "Scams or Fraud"),
                    (8, "False information"),
                ]
            ),
        ),
    ]
