# Generated by Django 4.2.6 on 2023-11-07 23:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_activitypost_description_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="activitypost",
            options={"verbose_name_plural": "Activity Posts"},
        ),
    ]
