# Generated by Django 4.2.6 on 2023-11-02 14:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("socialuser", "0002_alter_socialuser_pronouns"),
        ("posts", "0003_rename_poster_id_activitypost_social_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitypost",
            name="social_user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="socialuser.socialuser",
            ),
        ),
    ]
