# Generated by Django 4.2.6 on 2023-11-11 00:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_alter_activitypost_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="poster",
            new_name="commentPoster",
        ),
    ]
